---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: kruise-game-system
spec:
  ports:
    - port: 443
      targetPort: 9876
  selector:
    control-plane: controller-manager