# permissions for end users to edit gameserversets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gameserverset-editor-role
rules:
- apiGroups:
  - game.kruise.io
  resources:
  - gameserversets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.kruise.io
  resources:
  - gameserversets/status
  verbs:
  - get
